### PR TITLE
Improving commit encodings collection support

### PR DESCRIPTION
**Pull request by dr-orlovsky**
This is an alternative to #178 as a more systematic commit encoding refactoring addressing several issues and providing test coverage

### CODE REVIEW

**Comment by dr-orlovsky** [comment]
Rebased on a master tip which now has a fixed CI

**Comment by claudiosdc** [comment]
> This is an alternative to #178 as a more systematic commit encoding refactoring addressing several issues and providing test coverage

Sorry, but I do not see how this could be an alternative for PR #178 when the issue that it was trying to address had to do with implementation of `CommitEncode` for vectors (`Vec<T>`) and not collections in general.

To illustrate what I am saying, if you take the `collections()` test function that is included in this PR and replace the statement that declares the `collection` variable so that the collection is now a vector instead of a binary tree map (as shown below),

```rust
        /*let collection: BTreeMap<usize, Item> = bmap! {
            0 => Item(s!("My first case")),
            1 => Item(s!("My second case with a very long string")),
            3 => Item(s!("My third case to make the Merkle tree two layered"))
        };*/
        let collection = vec![
            Item(s!("My first case")),
            Item(s!("My second case with a very long string")),
            Item(s!("My third case to make the Merkle tree two layered")),
        ];
```

and try to (compile and) execute that test function,

```shell
cargo test -p client_side_validation collections
```

you will get the following error:

```shell
error[E0599]: no method named `commit_serialize` found for struct `Vec<Item>` in the current scope
   --> client_side_validation/src/commit_encode.rs:395:35
    |
395 |         println!("{}", collection.commit_serialize().to_hex());
    |                                   ^^^^^^^^^^^^^^^^ method not found in `Vec<Item>`
    | 
   ::: /Users/claudio/.cargo/registry/src/github.com-1ecc6299db9ec823/amplify-3.0.0/src/strategy.rs:86:1
    |
86  | pub struct Holder<T, S>(T, PhantomData<S>);
    | ------------------------------------------- doesn't satisfy `Holder<[Item], _>: commit_encode::CommitEncode`
    | 
   ::: /Users/claudio/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/vec.rs:300:1
    |
300 | pub struct Vec<T> {
    | -----------------
    | |
    | doesn't satisfy `Vec<Item>: commit_encode::CommitEncodeWithStrategy`
    | doesn't satisfy `Vec<Item>: commit_encode::CommitEncode`
    |
    = note: the method `commit_serialize` exists but the following trait bounds were not satisfied:
            `Vec<Item>: commit_encode::CommitEncodeWithStrategy`
            which is required by `Vec<Item>: commit_encode::CommitEncode`
            `[Item]: Sized`
            which is required by `[Item]: commit_encode::CommitEncode`
            `[Item]: commit_encode::CommitEncodeWithStrategy`
            which is required by `[Item]: commit_encode::CommitEncode`
            `[Item]: Clone`
            which is required by `[Item]: commit_encode::CommitEncode`
            `Holder<[Item], _>: commit_encode::CommitEncode`
            which is required by `[Item]: commit_encode::CommitEncode`
```

Showing that the `CommitEncode` trait is not automatically implemented for `Vec<T>` as it is for `BTreeMap<K,V>` and `BTreeSet<T>`.

**Comment by dr-orlovsky** [comment]
> Showing that the CommitEncode trait is not automatically implemented for Vec<T> as it is for BTreeMap<K,V> and BTreeSet<T>.

Correct, and that is done deliberately, as I commented in #178, otherwise we will have an unpredictable behavior. Each time you need `CommitEncode` on a specific vector type, you need to do `impl CommitEncodeWithStrategy for Vec<ConcreteType> { type Strategy = Merklization }` explicitly - no new trait is needed.

Even if you'd like to support arbitrary `Vec`, you need not a new trait but instead implementing generic patter like it's done in the original `commit_encode` code for `BTreeMap`/`BTreeSet`:

```rust
    impl<T> CommitEncodeWithStrategy for Vec<T> {
        type Strategy = Merklization;
    }
```

However I think this is quite risky and instead considering removing this auto implementations for `BTreeMap`/`BTreeSet` and having manual implementations on each concrete type.

**Comment by claudiosdc** [comment]
> Each time you need `CommitEncode` on a specific vector type, you need to do `impl CommitEncodeWithStrategy for Vec<ConcreteType> { type Strategy = Merklization }` explicitly - no new trait is needed.

Yes, that is what I initially thought and tried. However, this is not possible. For instance, if you try to do the following implementation in the `contract::assignments` module of the `rgb-core` crate (see code below),

```rust
impl CommitEncodeWithStrategy for Vec<OwnedState<PedersenStrategy>> {
    type Strategy = commit_strategy::Merklization;
}
```

you will get the following error when you try to compile the code:

```shell
error[E0117]: only traits defined in the current crate can be implemented for arbitrary types
  --> src/contract/assignments.rs:51:1
   |
51 | impl CommitEncodeWithStrategy for Vec<OwnedState<PedersenStrategy>> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^---------------------------------
   | |                                 |
   | |                                 `Vec` is not defined in the current crate
   | impl doesn't use only types from inside the current crate
   |
   = note: define and implement a trait or new type instead
```

**Comment by claudiosdc** [comment]
> Even if you'd like to support arbitrary `Vec`s, you need not a new trait but instead implementing generic pattern like it's currently done in the original `commit_encode` code for `BTreeMap`/`BTreeSet` https://github.com/LNP-BP/rust-lnpbp/blob/master/client_side_validation/src/client_side_validation.rs#L190-L195:
> 
> ```rust
>     impl<T> CommitEncodeWithStrategy for Vec<T> {
>         type Strategy = Merklization;
>     }
> ```

Unfortunately, this is also not possible because this generic implementation would conflict with the specific implementations for `Vec<u8>`, `Vec<u16>`, `Vec<u32>`, and `Vec<`u64`>` that already exist. I have also tried it.

**Comment by dr-orlovsky** [comment]
Right, you can't implement foreign traits on the foreign types (like `Vec` or `HashMap`). Thus we will need a generic implementation inside `client_side_verify`. It can be done by removing the existing implementations on different integers (since they are not needed anyway and will be covered by the generic implementation). I do not like such generalization, but afraid no other choice here... Will add a commit in a moment.

**Comment by dr-orlovsky** [comment]
@claudiosdc done with 6b29111188d55a456a85d7f76121cf77756fd432

**Comment by claudiosdc** [comment]
> @claudiosdc done with [6b29111](https://github.com/LNP-BP/rust-lnpbp/commit/6b29111188d55a456a85d7f76121cf77756fd432)

Yes, I guess this will do the trick. Thanks.

I believe we can close PR #178 in favor of this one.

**Comment by dr-orlovsky** [comment]
Thank you for catching that. I do not remember the reason behind that, but I assume I had it when I was doing all that custom implementations (instead of deriving `Vec` the same way I derived `BTreeSet`/`BTreeMap`, especially with this specific exclusion). Will do the investigation tomorrow.

**Pull request merged**
