### PR TITLE
Use 32-bit integers for transaction output indexes in single-use seals

### PR DESCRIPTION
**Pull request by rajarshimaitra**
This solves [Issue#45](https://github.com/LNP-BP/rust-lnpbp/issues/45)

The change is fairly trivial unless I am missing something.

Build + Tests passes.

### CODE REVIEW

**Comment by dr-orlovsky** [comment]
You do... I think you've tested without RGB and other features. Pls try running `./contrib/test.sh`. You can also check travis log here from the build https://github.com/LNP-BP/rust-lnpbp/pull/57/checks:

```console
error[E0308]: mismatched types
  --> src/rgb/contract/seal.rs:41:17
   |
41 |                 vout,
   |                 ^^^^
   |                 |
   |                 expected `u32`, found `u16`
   |                 help: you can convert an `u16` to `u32`: `vout: vout.into()`
error[E0308]: mismatched types
  --> src/rgb/contract/seal.rs:56:17
   |
56 |                 vout,
   |                 ^^^^
   |                 |
   |                 expected `u32`, found `u16`
   |                 help: you can convert an `u16` to `u32`: `vout: vout.into()`
error[E0308]: mismatched types
  --> src/rgb/contract/seal.rs:41:17
   |
41 |                 vout,
   |                 ^^^^
   |                 |
   |                 expected `u32`, found `u16`
   |                 help: you can convert an `u16` to `u32`: `vout: vout.into()`
error[E0308]: mismatched types
  --> src/rgb/contract/seal.rs:56:17
   |
56 |                 vout,
   |                 ^^^^
   |                 |
   |                 expected `u32`, found `u16`
   |                 help: you can convert an `u16` to `u32`: `vout: vout.into()`
```

**Comment by rajarshimaitra** [comment]
Yes, I have forgotten to run build with all the features. Thanks for pointing to `test.sh` helper. I have run the tests and made the required updates.
There is a failure in unit tests as 
```
test rgb::stash::consignment::test::test_consignment_validation ... FAILED
test lnpbps::elgamal::test::test_text_rand ... ok
test bp::dbc::pubkey::test::test_pubkey_commitment ... ok
test bp::dbc::keyset::test::test_keyset_commitment ... ok

failures:

---- rgb::stash::consignment::test::test_consignment_validation stdout ----
thread 'rgb::stash::consignment::test::test_consignment_validation' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedDataStructure("We support only homomorphic commitments to U64 data")', src/rgb/stash/consignment.rs:124:47


failures:
    rgb::stash::consignment::test::test_consignment_validation

test result: FAILED. 60 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

Which probably needs the updated consignment as per u32 vout.

 Will also check for rgb-node build and update if anything required over there.

**Comment by rajarshimaitra** [comment]
Ok, now two Travis builds are failing on the same error which is not happening in my local.

```
  --> src/rgb/contract/amount.rs:92:48
   |
92 |         match (&self.commitment.0).partial_cmp(&other.commitment.0[..]) {
   |                                                ^^^^^^^^^^^^^^^^^^^^^^^ expected array `[u8; 33]`, found slice `[u8]`
   |
   = note: expected reference `&[u8; 33]`
              found reference `&[u8]`
error[E0308]: mismatched types
  --> src/rgb/contract/amount.rs:92:48
   |
92 |         match (&self.commitment.0).partial_cmp(&other.commitment.0[..]) {
   |                                                ^^^^^^^^^^^^^^^^^^^^^^^ expected array `[u8; 33]`, found slice `[u8]`
   |
   = note: expected reference `&[u8; 33]`
              found reference `&[u8]`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0308`.
error: could not compile `lnpbp`.
```
Not exactly sure what's happening here. Need some help.

**Comment by rajarshimaitra** [comment]
The same issue is reported here in rgb-node 
https://github.com/LNP-BP/rgb-node/issues/28

It seems lnp-bp is failing on master and the cause is this commit https://github.com/LNP-BP/rust-lnpbp/commit/dbd0d324bf7762e8ddb7c88393ad70df5a96dc6e

Also rgb build is failing both in my local and in Travis. And this two are probably related. https://github.com/LNP-BP/rgb-node/issues/25

Working on a fix for lnp-bp first.

**Comment by dr-orlovsky** [comment]
They have updated rust nighty to the new version, and this have caused change in how the syntax is treated. I've pushed an updating commit, so pls rebase onto master (and now it won't work on the older compiler versions)

**Pull request merged**
